---
title: "R Notebook for Komack"
author: Canh Do
date: 6/2/2020
output: html_notebook
---

```{r, message = F, warning = F}
# Calling needed libraries
library(readr)
library(bbmle)
library(dplyr)
library(tidyverse)
library(pastecs)
library(compareDF)
```

# Multinomial Logit Model
## Individual Unit
There are 3 access mode choices with sample size of 1042 observations
Dummy codes as follows:
 1 (Motorbike); 2 (Private car); 3 (Taxi); 4 (Airport bus); 5 (VCAT)

### 1. First step:
+ Reading data from CSV file
```{r, message = F, warning = F}
     olddata <- read_csv("20200423_Data5.csv")
     newdata <- read_csv("20200528_Data.csv")
     #ctable <- compare_df(olddata, newdata, "ID")
     ctable <- compare_df(olddata[,c("Vehtime_MT", "Vehtime_Bus", "Vehtime_Car","Vehtime_Taxi","Vehtime_VCAT")], newdata[,c("Vehtime_MT", "Vehtime_Bus", "Vehtime_Car","Vehtime_Taxi","Vehtime_VCAT")])
     print(ctable$comparison_table_diff)
```
+ Summary
```{r, message = F, warning = F}
     #names(data)
     #summary(data)
     head(data)
     # str(data)
```

```{r}
CleaningData <- function (data = olddata)
 {
# Dummies (or indicator) for Laos people
    data$Laos <- ifelse(data$Nationality<=2,1,0) #Laos people
# Dummies (or indicator) for Vientiane residents
    data$Vien <- ifelse(data$Nationality==1,1,0) #Vientiane resident

# Dummies (or indicator) for Gender
    data$Male <- ifelse(data$Gender==1,1,0) #Male

# Dummies (or indicator) for data$Ag
     data$Age1 <- ifelse(data$Age==1,1,0) # <20
     data$Age2 <- ifelse(data$Age==2,1,0) # =21-30
     data$Age3 <- ifelse(data$Age==3,1,0) # =31-40
     data$Age4 <- ifelse(data$Age==4,1,0) # =41-50
     data$Age5 <- ifelse(data$Age==5,1,0) # =51-60
     data$Age6 <- ifelse(data$Age==6,1,0) # >60

# Dummies (or indicator) for Education
     data$Edu1 <- ifelse(data$Edu==1,1,0) # Highshool
     data$Edu2 <- ifelse(data$Edu==2,1,0) # College
     data$Edu3 <- ifelse(data$Edu==3,1,0) # Bachelor
     data$Edu4 <- ifelse(data$Edu==4,1,0) # Master
    data$HEdu <-ifelse(data$Edu >=2,1,0) # High Education

# Dummies (or indicator) for Occupation
     data$Job1 <- ifelse(data$Job==1,1,0) # Goverment offical + Dr/nurse + Prof/teacher.
     data$Job2 <- ifelse(data$Job==2,1,0) # Businessperson
     data$Job3 <- ifelse(data$Job==3,1,0) # Salesperson
     data$Job4 <- ifelse(data$Job==4,1,0) # Self-employed personr
     data$Job5 <- ifelse(data$Job==5,1,0) # Private-employess
     data$Job6 <- ifelse(data$Job==6,1,0) # Students
     data$Job7 <- ifelse(data$Job==7,1,0) # Housekeeper
     data$Job8 <- ifelse(data$Job==8,1,0) # Retired/Unemployed
     data$Job9 <- ifelse(data$Job==9,1,0) # Others

     data$HJob <- ifelse(data$Job <=5,1,0)

# Dummies (or indicator) for Monthly household income
     data$Hinc1 <- ifelse(data$Hinc==1,1,0) # Low 1,299,999
     data$Hinc2 <- ifelse(data$Hinc==2,1,0) # 1,300,000-1,999,999
     data$Hinc3 <- ifelse(data$Hinc==3,1,0) # 2,000,000-3,999,999
     data$Hinc4 <- ifelse(data$Hinc==4,1,0) # 4,000,000-6,999,999
     data$Hinc5 <- ifelse(data$Hinc==5,1,0) # 7,000,000-9,999,999
     data$Hinc6 <- ifelse(data$Hinc==6,1,0) # 10,000,000-14,999,999
     data$Hinc7 <- ifelse(data$Hinc==7,1,0) # 15,000,000-19,999,999
     data$Hinc8 <- ifelse(data$Hinc==8,1,0) # Above 20,000,000
    
     data$Inc <- ifelse(data$Hinc >6,1,0)

# Dummies (or indicator) for Dependency of others
     data$Dependence1 <- ifelse(data$Dependency==1,1,0) #Car-dropped
     data$Dependence2 <- ifelse(data$Dependency==2,1,0) #Car-parked
     data$Dependence3 <- ifelse(data$Dependency==3,1,0) #Shared ride

# Dummies (or indicator) for Household members
     data$Hmem1 <- ifelse(data$Hcar==1,1,0) # 1 member
     data$Hmem2 <- ifelse(data$Hcar==2,1,0) # 2 members
     data$Hmem3 <- ifelse(data$Hcar==3,1,0) # 3 members
     data$Hmem4 <- ifelse(data$Hcar==4,1,0) # 4 members
     data$Hmem5 <- ifelse(data$Hcar==5,1,0) # 5 members

# Dummies (or indicator) for Number of cars in a Household
     data$Hcar0 <- ifelse(data$Hcar==0,1,0) # no car
     data$Hcar1 <- ifelse(data$Hcar==1,1,0) # 1 car
     data$Hcar2 <- ifelse(data$Hcar==2,1,0) # 2 cars
     data$Hcar3 <- ifelse(data$Hcar==3,1,0) # 3 cars
     data$Hcar4 <- ifelse(data$Hcar==4,1,0) # 4 cars

# Dummies (or indicator) for Number of Check-in Luggage
     data$lug0 <- ifelse(data$ChLug==0,1,0) # no lug
     data$lug1 <- ifelse(data$ChLug==1,1,0) # 1 lug
     data$lug2 <- ifelse(data$ChLug==2,1,0) # 2 lug
     data$lug3 <- ifelse(data$ChLug==3,1,0) # 3 lug

# Dummies (or indicator) for Trip purpose
     data$tpp1 <- ifelse(data$Tpp==1,1,0) # business trip
     data$tpp2 <- ifelse(data$Tpp==2,1,0) # holiday trip
     data$tpp3 <- ifelse(data$Tpp==3,1,0) # education trip
     data$tpp4 <- ifelse(data$Tpp==4,1,0) # visiting/home trip

## Calculating new Travel time
     data$TT_MT = data$Vehtime_MT + data$Accesstime_MT + data$Wtime_MT + data$Safe_MT #+ data$Delay_MT
     data$TT_Car = data$Vehtime_Car + data$Accesstime_Car + data$Wtime_Car + data$Safe_Car
     data$TT_Taxi = data$Vehtime_Taxi + data$Accesstime_Taxi + data$Wtime_Taxi + data$Safe_Taxi #+ data$Delay_Taxi
     data$TT_Bus = data$Vehtime_Bus + data$Accesstime_Bus + data$Wtime_Bus + data$Safe_Bus
     data$TT_VCAT = data$Vehtime_VCAT + data$Accesstime_VCAT + data$Wtime_VCAT + data$Safe_VCAT

## Dummy variable for transfer
    data$NoTranfer_VCAT = 1

## Delay time
     data$Delay_MT = 0
     return(data)
}
```

### 2. Second step: Defining Log-likelihood function
```{r}
LL <- function (C.M,C.T,C.B,C.V,
                Cost,
                Parking,
                #TTime,
                Vehtime,
                #Delay,
                #Wait,
                #Access,
                Transfer#,
                 #Lao.M,
                 #Lao.T,
                 #Lao.B,
                 #Lao.V,
                 #Male.M,
                 #Male.T,
                 #Male.B,
                 #Male.V,
                 #Age60.M,
                 #Age60.T,
                 #Age60.B,
                 #Age60.V,
                 #HEdu.M,
                 #HEdu.T,
                 #HEdu.B,
                 #HEdu.V,
                 #HJob.M,
                 #HJob.T,
                 #HJob.B,
                 #HJob.V,
                 ##HInc.M,
                 ##HInc.T,
                 ##HInc.B,
                 ##HInc.V,
                 #Hcar.M,
                 #Hcar.T,
                 #Hcar.B,
                 #Hcar.V,
                 #Lug.M,
                 #Lug.T,
                 #Lug.B,
                 #Lug.V,
                 #Accom.M,
                 #Accom.T,
                 #Accom.B,
                 #Accom.V,
                 #BusiTrip.M,
                 #BusiTrip.T,
                 #BusiTrip.B,
                 #BusiTrip.V,
                 #Depen.C,
                 #Depen.M,
                 #Depen.T,
                 #Depen.V,
                 #Rain.C,
                 #Rain.T,
                 #Rain.B,
                 #Rain.V
 )
 { #Begin function

 # Utility function
 V.M <- C.M + data$TCost_MT*Cost +
             data$ParkFee_MT*Parking +
             #data$TT_MT*TTime
             data$Vehtime_MT*Vehtime +
             #data$Wtime_MT*Wait +
             # data$Accesstime_MT*Access +
             data$NoTranfer_MT*Transfer #+
             #data$Laos*Lao.M + data$Male*Male.M + data$HJob*HJob.M + data$Age6*Age60.M +
             #data$HEdu*HEdu.M + data$ChLug*Lug.M + data$Accom*Accom.M + data$Tpp*BusiTrip.M +
             #data$Dependency*Depen.M + data$Hcar*Hcar.M #+ data$Inc*HInc.M

 V.C <- 0 +  data$TCost_Car*Cost +
             data$ParkFee_Car*Parking +
             #data$TT_Car*TTime +
             data$Vehtime_Car*Vehtime +
             #data$Delay_Car*Delay +
             # + data$Wtime_Car*Wait + data$Accesstime_Car*Access
             data$NoTranfer_Car*Transfer #+
             #data$Dependency*Depen.C + data$WeaCon*Rain.C

 V.T <- C.T + data$TCost_Taxi*Cost +
             0 +
             #data$TT_Taxi*TTime
             data$Vehtime_Taxi*Vehtime +
             #data$Delay_Taxi*Delay +
             #+ data$Wtime_Taxi*Wait +
             # data$Accesstime_Taxi*Access +
             data$NoTranfer_Taxi*Transfer #+
             #data$Laos*Lao.T + data$Male*Male.T+ data$HJob*HJob.T + data$Age6*Age60.T +
             #data$HEdu*HEdu.T + data$ChLug*Lug.T + data$Accom*Accom.T + data$Tpp*BusiTrip.T +
             #0 + data$Hcar*Hcar.T + data$WeaCon*Rain.T + data$Dependency*Depen.T # + data$Inc*HInc.T

 V.B <- C.B + data$TCost_Bus*Cost +
             #data$TT_Bus*TTime
             data$Vehtime_Bus*Vehtime +
             #data$Delay_Bus*Delay +
             #data$Wtime_Bus*Wait +
             # data$Accesstime_Bus*Access +
             data$NoTranfer_Bus*Transfer #+
             #data$Laos*Lao.B+ data$Male*Male.B + data$HJob*HJob.B+ data$Age6*Age60.B+
             #data$HEdu*HEdu.B+ data$ChLug*Lug.B+ data$Accom*Accom.B+ data$Tpp*BusiTrip.B+
             #0 + data$Hcar*Hcar.B+ data$WeaCon*Rain.B#+ data$Inc*HInc.B

 V.V <- C.V + data$TCost_VCAT*Cost +
             #data$TT_VCAT*TTime
             data$Vehtime_VCAT*Vehtime +
             #data$Delay_VCAT*Delay +
             #data$Wtime_VCAT*Wait +
             #data$Accesstime_VCAT*Access +
             data$NoTranfer_VCAT*Transfer #+
             #data$Laos*Lao.V+ data$Male*Male.V + data$HJob*HJob.V+ data$Age6*Age60.V+
             #data$HEdu*HEdu.V+ data$ChLug*Lug.V+ data$Accom*Accom.V+ data$Tpp*BusiTrip.V+
             #0 + data$WeaCon*Rain.V+ data$Hcar*Hcar.V+ data$Dependency*Depen.V# + data$Inc*HInc.V

 # Denominator
 Sum <- exp(V.M) + exp(V.C) + exp(V.T) + exp(V.B) + exp(V.V)

 # Probabilities
 P.M <- exp(V.M)/Sum
 P.C <- exp(V.C)/Sum
 P.T <- exp(V.T)/Sum
 P.B <- exp(V.B)/Sum
 P.V <- exp(V.V)/Sum

 # Dummies (or indicator) for alternatives
 D.M <- ifelse(data$Mode == "Motorbike",1,0)
 D.C <- ifelse(data$Mode == "Car",1,0)
 D.T <- ifelse(data$Mode == "Taxi",1,0)
 D.B <- ifelse(data$Mode == "Bus",1,0)
 D.V <- ifelse(data$Mode == "VCAT",1,0)

 # Log-likelihood function
 L <- -(sum(D.M*log(P.M) + D.C*log(P.C) + D.T*log(P.T) + D.B*log(P.B) + D.V*log(P.V)))
 return(L)
} #End function
```

### 3. Third step: Model Estimation
```{r}
#<<< step>>>
#####  #####

 initValue <- list(C.M=0,C.T=0,C.B=0,C.V=0,
                    Cost=0,
                    Parking=0,
                    #TTime=0
                    Vehtime=0,
                    #Delay=0,
                    # Wait=0,
                    #Access=0,
                    Transfer=0#,
                    #Lao.M = 0,
                    #Lao.T = 0,
                    #Lao.B = 0,
                    #Lao.V = 0,
                    #Male.M = 0,
                    #Male.T = 0,
                    #Male.B = 0,
                    #Male.V = 0,
                    #Age60.M = 0,
                    #Age60.T = 0,
                    #Age60.B = 0,
                    #Age60.V = 0,
                    #HEdu.M = 0,
                    #HEdu.T = 0,
                    #HEdu.B = 0,
                    #HEdu.V = 0,
                    #HJob.M = 0,
                    #HJob.T = 0,
                    #HJob.B = 0,
                    #HJob.V = 0,
                    ## HInc.M = 0,
                    ## HInc.T = 0,
                    ## HInc.B = 0,
                    ##HInc.V = 0,
                    #Hcar.M = 0,
                    #Hcar.T = 0,
                    #Hcar.B = 0,
                    #Hcar.V = 0,
                    #Lug.M = 0,
                    #Lug.T = 0,
                    #Lug.B = 0,
                    #Lug.V = 0,
                    #Accom.M = 0,
                    #Accom.T = 0,
                    #Accom.B = 0,
                    #Accom.V = 0,
                    #BusiTrip.M = 0,
                    #BusiTrip.T = 0,
                    #BusiTrip.B = 0,
                    #BusiTrip.V = 0,
                    #Depen.C = 0,
                    #Depen.M = 0,
                    #Depen.T = 0,
                    #Depen.V = 0,
                    #Rain.C = 0,
                    #Rain.T = 0,
                    #Rain.B = 0,
                    #Rain.V = 0
)
 data <- CleaningData(data = olddata)
 MNL1 <- mle2(LL, start = initValue, method = "BFGS", control = list(trace = 1, maxit = 1e6))
 out1 <- summary(MNL1)
 out1
 data <- CleaningData(data = newdata)
 MNL2 <- mle2(LL, start = initValue, method = "BFGS", control = list(trace = 1, maxit = 1e6))
 out2 <- summary(MNL2)
 out2
```

```{r}
#<<<Fourth step>>>
  LL0     <- NROW(data)*log(1/5)     ## Initial log-likelihood
  LL1     <- logLik(MNL1)             ## Converged log-likelihood
  ## McFadden's Rho square
  Rho     <- 1-(LL1/LL0)
  Rho.adj <- 1-((LL1-length(coef(MNL1)))/LL0)
  GoF     <- cbind(LL0,LL1, Rho, Rho.adj)  ## Goodness of fit
  print(GoF)
```

```{r}
out_comp <- as.data.frame(out1@coef) %>% round(.,7) %>%
            rownames_to_column(var = "ParName") %>%
            separate(col = "ParName", into = c("ParName", "Mode"), sep = "([\\.])") %>%
            mutate(Mode = case_when(TRUE ~ Mode,
                                    Mode == "M" ~ "MotorBike",
                                    Mode == "C" ~ "Car",
                                    Mode == "T" ~ "Taxi",
                                    Mode == "B" ~ "Bus",
                                    Mode == "V" ~ "VCAT")
                  ) %>%
            mutate(Sign = case_when(Estimate >  0 ~ "Positive",
                                    Estimate <= 0 ~ "Negative")
                   ) %>%
            mutate(ParName = case_when(ParName == "Nat" ~ "Foreigner",
                                       ParName == "Gen" ~ "Male",
                                       ParName == "Job1" ~ "Goverment offical",
                                       ParName == "Job2" ~ "Businessperson",
                                       ParName == "Job3" ~ "Students",
                                       ParName == "Job4" ~ "Professor",
                                       ParName == "Job5" ~ "Salesperson",
                                       ParName == "Job6" ~ "Housekeeper",
                                       ParName == "Job7" ~ "Private firm employee",
                                       ParName == "Job8" ~ "Self-employes person",
                                       ParName == "Job9" ~ "Retired",
                                       ParName == "Job10" ~ "Others",
                                       ParName == "Age1" ~ "Age ~20",
                                       ParName == "Age2" ~ "Age 21-30",
                                       ParName == "Age3" ~ "Age 31-40",
                                       ParName == "Age4" ~ "Age 41-50",
                                       ParName == "Age5" ~ "Age 51-60",
                                       ParName == "Age6" ~ "Age >60",
                                       ParName == "Hinc1" ~ "Income (low)",
                                       ParName == "Hinc2" ~ "Income (Medium)",
                                       ParName == "Hinc3" ~ "Income (High)",
                                       ParName == "Hcar" ~ "Number of Cars",
                                       ParName == "C" ~ "Constant",
                                       TRUE ~ ParName)
                   ) %>%
           mutate(Mode = case_when(Mode == "M" ~ "Motorbike",
                                   Mode == "C" ~ "Car",
                                   Mode == "B" ~ "Bus",
                                   Mode == "T" ~ "Taxi",
                                   Mode == "V" ~ "VCAT",
                                   is.na(Mode) ~ "All modes",
                                   TRUE ~ Mode)
                    )%>%
            mutate(Impact = case_when(`Pr(z)` <=0.1 ~ "Significant",
                                      TRUE ~ "Unsignificant"))-> data_plot

 ggplot(data_plot,mapping = aes(x = ParName, y = Estimate, fill = Impact))+
         geom_col() +
         coord_flip() +
         facet_wrap(~ Mode)
```


